// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAallBluOKK3uLPXdfPpm5L-M8bhPBaxMI',
    appId: '1:529266323104:web:e6a551dcf0059a51cba3c5',
    messagingSenderId: '529266323104',
    projectId: 'foodly-flutter-app-338b9',
    authDomain: 'foodly-flutter-app-338b9.firebaseapp.com',
    storageBucket: 'foodly-flutter-app-338b9.firebasestorage.app',
    measurementId: 'G-EXV596ZT5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJMXiOial_wc5vRBZio0H9Kdh4htL7NX8', 
    appId: '1:529266323104:android:22eec9cf10970056cba3c5',
    messagingSenderId: '529266323104',
    projectId: 'foodly-flutter-app-338b9',
    storageBucket: 'foodly-flutter-app-338b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVcq7u3oDSyokPxNowG7vqDWp-1L19nz0',
    appId: '1:529266323104:ios:50501de49b6039f8cba3c5',
    messagingSenderId: '529266323104',
    projectId: 'foodly-flutter-app-338b9',
    storageBucket: 'foodly-flutter-app-338b9.firebasestorage.app',
    iosBundleId: 'com.example.restaurantFoodly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVcq7u3oDSyokPxNowG7vqDWp-1L19nz0',
    appId: '1:529266323104:ios:50501de49b6039f8cba3c5',
    messagingSenderId: '529266323104',
    projectId: 'foodly-flutter-app-338b9',
    storageBucket: 'foodly-flutter-app-338b9.firebasestorage.app',
    iosBundleId: 'com.example.restaurantFoodly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAallBluOKK3uLPXdfPpm5L-M8bhPBaxMI',
    appId: '1:529266323104:web:570ee7098f5dd535cba3c5',
    messagingSenderId: '529266323104',
    projectId: 'foodly-flutter-app-338b9',
    authDomain: 'foodly-flutter-app-338b9.firebaseapp.com',
    storageBucket: 'foodly-flutter-app-338b9.firebasestorage.app',
    measurementId: 'G-1FRNGFDHEG',
  );
}
